// Code generated by protoc-gen-byteplus-sdk
// source: VodSpaceService
// DO NOT EDIT!

package vod

import (
	"fmt"
	"testing"

	"github.com/byteplus-sdk/byteplus-sdk-golang/base"
	"github.com/byteplus-sdk/byteplus-sdk-golang/service/vod"
	"github.com/byteplus-sdk/byteplus-sdk-golang/service/vod/models/request"
)

func Test_ListSpace(t *testing.T) {
	instance := vod.NewInstance()
	instance.SetCredential(base.Credentials{
		AccessKeyID:     "your ak",
		SecretAccessKey: "your sk",
	})

	query := &request.VodListSpaceRequest{
		Offset: 0,
		Limit:  0,
	}

	resp, status, err := instance.ListSpace(query)
	fmt.Println(status)
	fmt.Println(err)
	fmt.Println(resp.String())
}

func Test_UpdateSpaceUploadConfig(t *testing.T) {
	instance := vod.NewInstance()
	instance.SetCredential(base.Credentials{
		AccessKeyID:     "your ak",
		SecretAccessKey: "your sk",
	})

	query := &request.VodUpdateSpaceUploadConfigRequest{
		SpaceName:   "your SpaceName",
		ConfigKey:   "your ConfigKey",
		ConfigValue: "your ConfigValue",
	}

	resp, status, err := instance.UpdateSpaceUploadConfig(query)
	fmt.Println(status)
	fmt.Println(err)
	fmt.Println(resp.String())
}
