// Code generated by protoc-gen-byteplus-sdk
// source: VodDrmService
// DO NOT EDIT!

package vod

import (
	"fmt"
	"testing"

	"github.com/byteplus-sdk/byteplus-sdk-golang/service/vod"
	"github.com/byteplus-sdk/byteplus-sdk-golang/service/vod/models/request"
)

func Test_GetThirdPartyDrmAuthToken(t *testing.T) {
	vid := "your vid"
	tokenExpireTime := 600 // Token Expire Duration（s）
	instance := vod.NewInstance()

	//instance.SetCredential(base.Credentials{
	// AccessKeyID:     "your ak",
	// SecretAccessKey: "your sk",
	//})

	// or set ak and ak as follow
	instance.SetAccessKey("your ak")
	instance.SetSecretKey("your sk")

	query := &request.VodGetDrmLicenseRequest{
		Vid:               vid,
		ThirdPartyDrmType: "your DrmType",
		Persistent:        0,
		LicenseDuration:   0,
	}
	newToken, err := instance.GetThirdPartyDrmAuthToken(query, tokenExpireTime)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(newToken)
}
